travis:
  secure:
    BINSTAR_TOKEN: iRzeS+aJn6P2/E7FK+qg5KKOCjokbpMnHUBknMt9XD018vprZupMvQ+5Bz1lND4agrAEjEfmLzBPHFlWXDT0VoDZeWIcxa3XERiyOrUHkJhRLgEzQqORViNxem2UWaTzCNt4lmZ2gLdwAhKYaWsrQxJtwDLlr5VtRf9m/md/AlDIIJ5/WDCYjDTi8XFJwC6g40VDG9Fhma0NtnM7F5ACRkUnMmWM39e/C2OKD3UECA6KEbXVmrjork/gFu6gFn573jD5xxIZXcb/olPRBuSLuzIUNDnjNNHOEy4PgepVblXFKoAQmUIun0mn7bDKlzGGZZAOsdA9oTQDFXPP592SJfq9x1mx2LB/+hseKep/MBOpA7eLMHO66RnVZRBgsoeZ/4AcsqBdsd8GjxfsBDqD6O/u90NgCK86zXTm7slLD+fL8VbASrAkuO1xZBKQQK1SIobh8IsDa3h+CVP6tYpHEkVGcNzMLivFmxdHAtwQVLrotshiDYWISWTrfxrvKAE54zpTBS76z0LpkcW1cMtbOLmFqQKnqIrWs46N8CA544uOUhjdIafuIFYPPzMpsCZu4reXAW8rvQIMEQpzvnWDjHrPsEUvz9pfkjvbt9rl8Vpk3jebLKvk/HR5PH65K98JXat0N4Ide7HMsU0kOrYuhh5eqKQlhNQ6TkIoHBFg7M8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
